In [ ]:
import numpy as np
a= np.array([[1, 2, 3, 4, 5],[9, 8, 7, 6, 5]])
np.zeros((2,3,7,7))

In [5]:
# All 1s Matrix
np.ones((2,3,7,7), dtype='int32')

array([[[[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1]

In [6]:
# Any other number's matrix
np.full((2,3,7,7), fill_value= 27)

array([[[[27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27]],

        [[27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27]],

        [[27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27]]],


       [[[27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27, 27, 27, 27, 27, 27],
         [27, 27,

In [7]:
# Any other matrix which has the same shape to that of an exisiting one but different elements/items in it
np.full_like(a= a, fill_value= 10, dtype= 'int64')

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]], dtype=int64)

In [8]:
# Random Decimal Number Array
np.random.rand(3,5,2)

array([[[0.84405951, 0.45652317],
        [0.58197451, 0.44644613],
        [0.65653837, 0.80612967],
        [0.56409988, 0.04308173],
        [0.47416275, 0.7998387 ]],

       [[0.85167121, 0.54250502],
        [0.25682035, 0.82778897],
        [0.9257303 , 0.95657186],
        [0.03343136, 0.63132552],
        [0.29315093, 0.39062962]],

       [[0.31115773, 0.1312862 ],
        [0.39915168, 0.91651958],
        [0.54853053, 0.93747798],
        [0.2792987 , 0.05119294],
        [0.15059385, 0.67488148]]])

In [9]:
# Random Integer Arrays
np.random.randint(low= 10000000000, high= 100000000000000, size= (10,15), dtype= 'int64')

array([[85823368781691, 45406706730362, 43155967187255, 89079467651921,
        43264397569610, 97320420651515, 18157666969995, 84587671711651,
        70827059141892, 34284268198815, 19796060699065, 74537218361718,
         4252597020256,  2207262463898, 18097235327371],
       [ 2136783249114, 87630385547335, 55239530561492, 41515252617240,
        27402713178270, 35105410868229, 19083958683623, 91138738381934,
        10945083132565, 26296800986363, 69041922042529,  8782734502597,
        70874680175477, 22107577202668, 12626741111820],
       [ 2261521970331, 66990368768901, 45054183932926, 17731337684314,
        21064052977786, 67249535518371, 61658078521232, 28376843857455,
        67466980202298,  4081608080776, 40977089481661, 66783380219933,
        77463843749776, 38338548427555, 25178215348774],
       [44287694853663, 85230326220075,  1112560082861, 61845765321237,
        35232212601209, 47288858247728, 67225030560605, 76625413335250,
        51335101170473, 6075900060827

In [10]:
# The identity function in numpy makes a sqaure array with 1s on the main diagonal. Number
# of rows and columns in n x n output
np.identity(10, dtype= 'int64') 


array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [11]:
# Repeating an Array
b = np.array([[[1,2,3,4,5],[6,7,8,9,0]]])
b_copy = np.repeat(a= b, repeats= 10, axis= 1)
b_copy

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0],
        [6, 7, 8, 9, 0],
        [6, 7, 8, 9, 0],
        [6, 7, 8, 9, 0],
        [6, 7, 8, 9, 0],
        [6, 7, 8, 9, 0],
        [6, 7, 8, 9, 0],
        [6, 7, 8, 9, 0],
        [6, 7, 8, 9, 0],
        [6, 7, 8, 9, 0]]])

In [19]:
# Exercise
x = np.ones((5,5))
y = np.zeros((3,3))
y[1,1]= 9
x[1:4, 1:4]=y
print(x)
# Be Careful when copying arrays !!!!!

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
# Copying an Array
z = a.copy()
print(z)

[[1 2 3 4 5]
 [9 8 7 6 5]]
