In [1]:
import numpy as np
import numpy as np
a = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14]])
print(a)

[list([1, 2, 3, 4, 5, 6, 7, 8]) list([9, 10, 11, 12, 13, 14])]


In [2]:
# Making arrays using NumPy Library
a = np.array([9, 10, 11, 12], dtype = 'int32')
b = np.array([[10, 15, 29, 31],[981, 100, 1983, 932]], dtype = 'int16')
print(f'{a}\n \n{b}')

[ 9 10 11 12]
 
[[  10   15   29   31]
 [ 981  100 1983  932]]


In [3]:
# Getting the types of the arrays using NumPy. We cam use the dtype parameter to specify what kind of array data do we need. Refer from above
print(a.dtype)
print(b.dtype)

int32
int16


In [4]:
# GETTING THE SIZE OF AN ARRAY

# Getting the size of each item 
print(a.itemsize)
print(b.itemsize)
print()

# Getting the length or the number of elements present in the array
print(a.size)
print(b.size)
print()

# Getting the total size of an array
print(a.nbytes)
print(b.nbytes)


4
2

4
8

16
16


In [5]:
# Getting the dimension of the arrays as the arrays in NumPy are multidimensional
print(f'{a.ndim} \n \n {b.ndim}')

1 
 
 2


In [6]:
# Getting the shape of the arrays which means the rows and columns of the arrays using NumPy. You can use this method to change the structure of an array.
print(a.shape)
print(b.shape)

(4,)
(2, 4)
